// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuTd9mt8z-7MJKek5XekxWfgX4GZ9XqW8',
    appId: '1:333671900333:web:105d06b367c539bf671224',
    messagingSenderId: '333671900333',
    projectId: 'chat-2ef4c',
    authDomain: 'chat-2ef4c.firebaseapp.com',
    storageBucket: 'chat-2ef4c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA61tFfpQcnUPvrlSBJyHbpiUnqyvu79cE',
    appId: '1:333671900333:android:adb0d57fb82d3be8671224',
    messagingSenderId: '333671900333',
    projectId: 'chat-2ef4c',
    storageBucket: 'chat-2ef4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbH4gyqnZwnt6mjTYD_ELcpyAVx7aczOE',
    appId: '1:333671900333:ios:b361a149efbdcc12671224',
    messagingSenderId: '333671900333',
    projectId: 'chat-2ef4c',
    storageBucket: 'chat-2ef4c.appspot.com',
    iosClientId: '333671900333-epa38c6hcieqho01iv2sviln79tdo5e3.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatappTaskT2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbH4gyqnZwnt6mjTYD_ELcpyAVx7aczOE',
    appId: '1:333671900333:ios:586dadbcc9e7b72d671224',
    messagingSenderId: '333671900333',
    projectId: 'chat-2ef4c',
    storageBucket: 'chat-2ef4c.appspot.com',
    iosClientId: '333671900333-i41bdvrl6eg1hmvsp5kd7aef9ru3d913.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatappTaskT2.RunnerTests',
  );
}
